apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  labels:
    run: my-python-app
  namespace: apps
spec:
  type: NodePort
  ports:
    - port: 32456
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: my-python-app
